<?php
// Generate syllabus SQL from structured data
$classes = [
["class"=>"Class 1","subjects"=>[
["name"=>"Maths","topics"=>["Pre-Number Concepts","Numbers 1-100","Place Value (Tens and Ones)","Comparison of Numbers","Addition","Subtraction","Introduction to Multiplication (Repeated Addition)","Introduction to Division (Equal Sharing)","Shapes (2D and 3D)","Patterns","Measurement (Length, Weight, Capacity)","Time (Days, Months, O'Clock)","Money","Data Handling (Picture Graphs)","Spatial Understanding","Applied Mathematics (Daily Life Maths)"]],
["name"=>"English Grammar","topics"=>["Alphabet (Capital and Small Letters)","Vowels and Consonants","Phonics and Letter Sounds","Blending and Word Formation","Naming Words (Nouns)","Common and Proper Nouns (Basic Introduction)","One and Many (Singular and Plural)","Gender (He/She)","Use of A and An","This and That","These and Those","Pronouns (He, She, It, They)","Describing Words (Adjectives)","Action Words (Verbs)","Is, Am, Are","Has and Have","Simple Present Tense","Sentence Formation","Capital Letter and Full Stop","Question Words (What, Where, Who)","Prepositions (In, On, Under, Behind)","Joining Words (And)","Opposites","Rhyming Words","Picture Composition (Oral)","Reading Simple Sentences","Listening and Speaking Skills"]],
["name"=>"EVS","topics"=>["Our Universe","Myself and My Body","Plants and Animals","Our Family","Our Neighbourhood","Weather, Air and Water","Transport and Communication","Means of Communication","Occasions and Festivals","Our Environment","Living and Non-Living Things","Types of Materials","Uses of Materials","Safety and Good Habits","Food We Eat","Clothes We Wear","Houses We Live In","Seasons","Occupations and Community Helpers","Famous Personalities of India","Natural Resources","Pollution and Conservation","Good Touch and Bad Touch (Basic Awareness)","Road Safety Rules","Reduce, Reuse, Recycle"]],
["name"=>"Social Science","topics"=>["Ourself and Our Family","Our Neighbourhood","My School and Community","Rules and Responsibilities","Good Citizenship","National Symbols of India","Our Country India (Basic Introduction)","States and Capitals (Basic Awareness)","Land and Water Forms","Directions (North, South, East, West)","Weather and Seasons","Transport","Communication","Occupations and Community Helpers","Festivals of India","Famous Indian Leaders","Maps and Globes (Basic Introduction)","Safety Rules (Home and Road)","Our Environment","Caring for Public Property"]],
]],
["class"=>"Class 2","subjects"=>[
["name"=>"Maths","topics"=>["Revision of Numbers up to 100","Numbers up to 1000","Place Value (Hundreds, Tens and Ones)","Expanded and Short Form","Comparison of Numbers","Ascending and Descending Order","Addition (2 and 3 Digit)","Subtraction (With and Without Borrowing)","Multiplication (Repeated Addition and Tables 2-10)","Division (Equal Sharing and Grouping)","Odd and Even Numbers","Ordinal Numbers","Fractions (Half, One-Third, One-Fourth)","Measurement of Length","Measurement of Weight","Measurement of Capacity","Time (Clock, Calendar)","Money (Addition and Subtraction of Money)","Shapes (2D and 3D)","Patterns","Data Handling (Pictographs and Tally Marks)","Basic Geometry (Lines and Curves)","Spatial Understanding","Word Problems (Daily Life Maths)","Mental Mathematics"]],
["name"=>"English Grammar","topics"=>["Alphabetical Order","Vowels and Consonants","Phonics and Blends","Nouns (Naming Words)","Common and Proper Nouns","Singular and Plural","Gender (Masculine and Feminine)","Pronouns","Adjectives (Describing Words)","Verbs (Action Words)","Is, Am, Are","Was and Were (Basic)","Has and Have","Simple Present Tense","Simple Past Tense (Basic)","Articles (A, An, The)","Prepositions (In, On, Under, Behind, Between)","Conjunctions (And, But)","Adverbs (Basic Introduction)","Sentence Formation","Kinds of Sentences (Statement, Question, Command, Exclamation)","Capital Letters and Punctuation","Question Words (Who, What, When, Where, Why, How)","Opposites","Synonyms (Basic)","Homophones (Basic)","Paragraph Writing (Guided)","Picture Composition","Comprehension (Unseen Passage)","Listening and Speaking Skills"]],
["name"=>"EVS","topics"=>["Myself and My Family","Our Body and Healthy Habits","Food We Eat","Clothes We Wear","Houses We Live In","Our Neighbourhood","People Who Help Us (Community Helpers)","Transport and Communication","Means of Communication","Plants Around Us","Uses of Plants","Animals Around Us","Wild and Domestic Animals","Living and Non-Living Things","Air, Water and Weather","Seasons","Sources of Water","Uses of Water and Water Conservation","Types of Materials","Uses of Materials","Safety Rules (Home and Road)","Festivals of India","Occupations","Our Environment and Cleanliness","Reduce, Reuse and Recycle","Simple Machines (Basic Introduction)","Solar System (Basic Awareness)"]],
["name"=>"Social Science","topics"=>["Myself and My Family","Our Neighbourhood","My School and Community","Rules and Responsibilities","Good Manners and Good Citizenship","National Symbols of India","Our Country India (Basic Introduction)","States and Capitals (Basic Awareness)","Directions (North, South, East, West)","Maps and Globe (Basic Introduction)","Landforms (Mountains, Plains, Rivers, Deserts)","Weather and Seasons","Transport","Communication","Occupations and Community Helpers","Festivals of India","Famous Indian Leaders and Personalities","Safety Rules (Home, School and Road)","Caring for Public Property","Our Environment and Natural Resources"]],
]],
["class"=>"Class 3","subjects"=>[
["name"=>"Maths","topics"=>["Number System (4-5 Digit Numbers)","Place Value and Face Value","Expanded Form and Short Form","Comparison and Ordering of Numbers","Roman Numerals (I-L)","Addition (4 Digit)","Subtraction (With and Without Borrowing)","Multiplication (2 and 3 Digit by 1 Digit)","Division (Basic Long Division)","Properties of Multiplication","Fractions (Like Fractions and Comparison)","Introduction to Geometry","Lines (Straight, Curved, Parallel, Intersecting)","2D and 3D Shapes","Patterns and Symmetry","Measurement of Length","Measurement of Weight","Measurement of Capacity","Perimeter (Basic Introduction)","Area (Counting Squares Method)","Time (Clock and Calendar)","Money (Bills and Word Problems)","Data Handling (Pictographs and Bar Graphs)","Mental Mathematics","Word Problems (Daily Life Applications)"]],
["name"=>"English Grammar","topics"=>["Alphabetical Order and Dictionary Skills","Nouns (Common, Proper and Collective)","Countable and Uncountable Nouns","Singular and Plural","Gender","Pronouns (Personal and Possessive)","Adjectives (Quality, Quantity and Number)","Comparison of Adjectives","Articles (A, An, The)","Verbs (Action and Helping Verbs)","Subject-Verb Agreement (Basic)","Simple Present Tense","Simple Past Tense","Simple Future Tense (Basic)","Adverbs (Introduction)","Prepositions","Conjunctions (And, But, Or)","Interjections","Kinds of Sentences","Sentence Formation and Word Order","Negative Sentences","Interrogative Sentences","Punctuation (Capital Letters, Full Stop, Comma, Question Mark, Exclamation Mark)","Opposites and Synonyms","Homophones (Basic)","Idioms (Basic Introduction)","Paragraph Writing","Letter Writing (Informal)","Comprehension (Unseen Passage)","Picture Composition","Listening and Speaking Skills"]],
["name"=>"EVS","topics"=>["Our Universe","The Solar System","The Earth and Its Features","Measurement (Basic Scientific Measurement)","Soil and Its Types","Our Environment","Living and Non-Living Things","Plants Around Us","Animals Around Us","Birds and Their Bodies","Human Body (Organs and Organ Systems)","Safety and First Aid","States of Matter (Solid, Liquid and Gas)","Housing and Clothing","Materials Around Us (What Things Are Made Of)","Light and Sound","Air and Water","Weather and Seasons","Sources of Energy (How Things Work)","Journey of a River","Natural Resources and Conservation","Our Vibrant Country (India - Physical and Cultural Features)","Some Unique Places of India","Pollution and Its Control","Food and Digestion (Basic Introduction)","Simple Machines (Basic Introduction)","Reduce, Reuse and Recycle"]],
["name"=>"Social Science","topics"=>["My Family and I","Our Neighbourhood and Community","Our School and Responsibilities","Good Citizenship and Civic Sense","India - Our Country","States and Union Territories","National Symbols of India","Physical Features of India","Maps and Directions","Globe and the Earth","Landforms (Mountains, Plains, Plateaus, Deserts, Islands)","Water Bodies (Rivers, Seas, Oceans)","Weather and Climate","Natural Resources","Transport and Communication","Occupations and Industries (Basic Introduction)","Rural and Urban Life","Festivals and Cultural Diversity of India","Famous Indian Leaders and Personalities","Monuments and Heritage Sites","Safety and Disaster Management (Basic)","Caring for the Environment","Local Government (Basic Introduction)","Journey of a River","Our Rights and Duties (Basic Introduction)"]],
]],
["class"=>"Class 4","subjects"=>[
["name"=>"Maths","topics"=>["Building with Bricks","Long and Short","A Trip to Bhopal","Tick Tick Tick (Time)","The Way the World Looks (Shapes and Mapping)","The Junk Seller (Money)","Jugs and Mugs (Capacity)","Carts and Wheels (Multiplication)","Numbers (Large Numbers and Place Value)","Addition and Subtraction","Multiplication","Division","Factors and Multiples","LCM and HCF","Fractions","Decimals","Time","Geometry (Lines, Angles and Shapes)","Measurement (Length, Weight and Capacity)","Perimeter","Money","Symmetry and Patterns","Data Handling / Pictograph"]],
["name"=>"English Grammar","topics"=>["Nouns (Common, Proper, Collective, Abstract)","Countable and Uncountable Nouns","Singular and Plural","Gender","Pronouns (Personal, Possessive, Reflexive)","Adjectives (Quality, Quantity, Number)","Degrees of Comparison","Articles (A, An, The)","Verbs (Main and Helping Verbs)","Subject-Verb Agreement","Simple Present Tense","Simple Past Tense","Simple Future Tense","Present Continuous Tense","Past Continuous Tense (Basic)","Adverbs","Prepositions","Conjunctions","Interjections","Kinds of Sentences","Negative and Interrogative Sentences","Active and Passive Voice (Basic Introduction)","Direct and Indirect Speech (Basic)","Punctuation (Comma, Apostrophe, Quotation Marks)","Synonyms and Antonyms","Homophones","Idioms and Proverbs (Basic)","Paragraph Writing","Letter Writing (Informal and Formal - Basic)","Comprehension (Unseen Passage)","Story Writing","Picture Composition","Listening and Speaking Skills"]],
["name"=>"EVS","topics"=>["Going to School (Transport and Safety)","Food for Plants (Photosynthesis - Basic Introduction)","States of Matter (Solid, Liquid and Gas)","Force and Energy","Adaptations in Plants","Adaptations in Animals","Clothes We Wear","Food - Our Basic Need","Teeth and the Digestive System","Circulatory and Respiratory Systems","Fibre and Fabric","The Solar System and Types of Planets","The Earth and the Sky","Natural Resources","Forests and Wildlife","Water and Its Conservation","Air and Pollution","Soil and Its Types","Weather and Seasons","Simple Machines","Safety and First Aid","Our Environment and Conservation"]],
["name"=>"Social Science","topics"=>["My Family and Community","Our Society and Diversity","India - Our Motherland","States and Union Territories of India","Physical Features of India","The Northern Mountains","The Northern Plains","The Desert Region","The Coastal Plains and Islands","Climate of India","Natural Vegetation and Wildlife","Soil and Natural Resources","Agriculture and Occupations","Transport and Communication","Our Government (Local Government - Panchayat and Municipality)","Rights and Duties of Citizens","National Symbols and National Leaders","Our Cultural Heritage","Famous Monuments of India","Maps and Globes","Latitudes and Longitudes (Basic Introduction)","Disaster Management (Basic)","Caring for the Environment","Industries of India (Basic Introduction)","Rural and Urban Administration"]],
]],
["class"=>"Class 5","subjects"=>[
["name"=>"Maths","topics"=>["Large Numbers and Roman Numerals","Operations on Whole Numbers","Tests of Divisibility","Factors and Multiples","LCM and HCF","Fractions","Decimals","Ratio and Proportion","Measurement (Length, Weight and Capacity)","Time and Temperature","Mensuration","Perimeter and Area","Volume (Basic Introduction)","Geometry and Geometrical Figures","Angles and Lines","Data Handling (Bar Graph and Line Graph)","BODMAS Rule","Arithmetic Operations","Profit and Loss","Percentage","Average","Speed, Time and Distance","Unitary Method","Applied Mathematics (Word Problems and Daily Life Applications)","Mental Mathematics"]],
["name"=>"English Grammar","topics"=>["Nouns (Common, Proper, Collective, Abstract)","Countable and Uncountable Nouns","Gender","Pronouns (Personal, Possessive, Reflexive, Demonstrative)","Adjectives and Degrees of Comparison","Articles (A, An, The)","Verbs (Main and Auxiliary)","Subject-Verb Agreement","Tenses (Simple Present, Past, Future)","Continuous Tenses (Present and Past)","Perfect Tense (Basic Introduction)","Adverbs (Manner, Time, Place)","Prepositions","Conjunctions","Interjections","Kinds of Sentences","Negative and Interrogative Sentences","Active and Passive Voice (Basic)","Direct and Indirect Speech (Basic)","Punctuation (Comma, Apostrophe, Quotation Marks, Colon)","Synonyms and Antonyms","Homophones and Homonyms","Idioms and Proverbs","Vocabulary Building","Paragraph Writing","Letter Writing (Formal and Informal)","Notice Writing (Basic)","Essay Writing","Story Writing","Comprehension (Unseen Passage)","Listening and Speaking Skills"]],
["name"=>"EVS","topics"=>["Food - Where Does It Come From","Human Body (Skeletal and Muscular System)","The Nervous System","Work and Play (Health and Hygiene)","Plants Around Us","Reproduction in Plants","Ecosystem and Food Chain","Our Environment","Environmental Issues and Conservation","Pollution (Air, Water, Land and Noise)","Natural Calamities and Disaster Management","Safety and First Aid","The Solar System","Earth, Moon and Sun","Movement of the Earth and Seasons","Weather, Air and Water","Matter in Our Surroundings","Properties of Matter and Materials","Work, Force and Energy","Simple Machines","Light and Sound","Rocks and Soil","Shelter and Housing","Travel and Communication","Grasslands and Forests","Soil Conservation","The Moon (Phases and Features)","Natural Resources and Their Conservation"]],
["name"=>"Social Science","topics"=>["Our Country - India","Latitudes and Longitudes","Movements of the Earth","Major Landforms of the World","Climate and Weather","Natural Vegetation and Wildlife","Water Resources","Agriculture and Industries","Transport and Communication","Natural Resources and Conservation","The United Nations (Basic Introduction)","Indian Freedom Struggle (Basic Overview)","National Leaders of India","The Constitution of India (Basic Introduction)","Fundamental Rights and Duties","Local Self-Government (Panchayati Raj and Municipal Corporation)","Rural and Urban Administration","Democracy and Government","Population and Occupations","Disaster Management","Environmental Issues","Heritage and Culture of India","Monuments and Historical Places","Maps and Globes","Continents and Oceans"]],
]],
["class"=>"Class 6","subjects"=>[
["name"=>"Maths","topics"=>["Patterns in Mathematics","Lines and Angles","Number Play","Data Handling and Presentation","Prime Time","Perimeter and Area","Fractions","Playing with Constructions","Symmetry","The Other Side of Zero"]],
["name"=>"Science","topics"=>["The Wonderful World of Science","Diversity in the Living World","Mindful Eating: A Path to a Healthy Body","Exploring Magnets","Measurement of Length and Motion","Materials Around Us","Temperature and Its Measurement","A Journey Through States of Water","Methods of Separation in Everyday Life","Living Creatures: Exploring Their Characteristics","Nature's Treasures","Beyond Earth"]],
["name"=>"English Grammar","topics"=>["Nouns (Kinds of Nouns)","Number and Gender","Pronouns","Adjectives","Articles (A, An, The)","Verbs (Transitive and Intransitive)","Subject-Verb Agreement","Tenses (Present, Past, Future)","Continuous and Perfect Tenses (Basic)","Adverbs","Prepositions","Conjunctions","Interjections","Kinds of Sentences","Active and Passive Voice (Introduction)","Direct and Indirect Speech (Introduction)","Punctuation","Degrees of Comparison","Modals (Can, May, Must, Should)","Synonyms and Antonyms","Homophones and Homonyms","Idioms and Phrases","Vocabulary Building","Sentence Transformation","Paragraph Writing","Letter Writing (Formal and Informal)","Notice Writing","Message Writing","Story Writing","Comprehension (Unseen Passage)"]],
["name"=>"Social Science","topics"=>["Locating Places on the Earth","Oceans and Continents","Landforms and Life","Timeline and Sources of History","India, That Is Bharat","The Beginnings of Indian Civilisation","India's Cultural Roots","Unity in Diversity, or Many in the One","Family and Community","Grassroots Democracy - Part 1: Governance","Grassroots Democracy - Part 2: Local Government in Rural Areas","Grassroots Democracy - Part 3: Local Government in Urban Areas","The Value of Work","Economic Activities Around Us"]],
]],
["class"=>"Class 7","subjects"=>[
["name"=>"Maths","topics"=>["Large Numbers Around Us","Arithmetic Expressions","A Peek Beyond the Point (Decimals)","Expressions Using Letter Numbers (Algebra)","Parallel and Intersecting Lines","Number Play","A Tale of Three Intersecting Lines (Triangles)","Working with Fractions"]],
["name"=>"Science","topics"=>["The Ever-Evolving World of Science","Exploring Substances: Acidic, Basic, Neutral","Electricity: Circuits and Their Components","The World of Metals and Non-Metals","Changes Around Us: Physical and Chemical","Adolescence: A Stage of Growth and Change","Heat Transfer in Nature","Measurement of Time and Motion","Life Processes in Animals","Life Processes in Plants","Light: Shadows and Reflections","Earth, Moon, and the Sun"]],
["name"=>"English Grammar","topics"=>["Nouns (Kinds and Functions)","Pronouns and Their Types","Adjectives and Degrees of Comparison","Articles and Determiners","Verbs (Transitive and Intransitive)","Subject-Verb Agreement","Tenses (Present, Past and Future)","Perfect and Continuous Tenses","Modals","Adverbs","Prepositions","Conjunctions","Interjections","Active and Passive Voice","Direct and Indirect Speech","Punctuation","Kinds of Sentences","Sentence Transformation","Phrases and Clauses","Synonyms and Antonyms","Homophones","Idioms and Phrases","Paragraph Writing","Letter Writing (Formal and Informal)","Notice Writing","Story Writing","Comprehension (Unseen Passage)"]],
["name"=>"Social Science","topics"=>["Geographical Diversity of India","Understanding the Weather","Climate of India","New Beginnings: Cities and States","The Rise of Empires","The Age of Reorganisation","The Gupta Era: An Age of Creativity","How the Land Becomes Sacred","From the Rulers to the Ruled: Types of Governments","The Constitution of India: An Introduction","From Barter to Money","Understanding Markets","The Story of Indian Farming","India and Her Neighbours","Empires and Kingdoms: 6th to 10th Centuries","Turning Tides: 11th and 12th Centuries","India, a Home to Many","The State, the Government, and You","Infrastructure: Engine of India's Development","Banks and the Magic of Finance"]],
]],
["class"=>"Class 8","subjects"=>[
["name"=>"Maths","topics"=>["Squares and Square Roots, Cubes and Cube Roots","Exponents and Powers","Rational Numbers","Understanding Quadrilaterals","Playing with Numbers","Algebraic Expressions and Identities, Factorisation","Direct and Inverse Proportions","Fractions in Disguise","Pythagoras Theorem","Comparing Quantities","Practical Geometry","Geometric Constructions","Linear Equations in One Variable","Mensuration (Area)"]],
["name"=>"Science","topics"=>["Exploring the Investigative World of Science","The Invisible Living World: Beyond Our Naked Eye","Health: The Ultimate Treasure","Electricity: Magnetic and Heating Effects","Exploring Forces","Pressure, Winds, Storms and Cyclones","Particulate Nature of Matter","Nature of Matter: Elements, Compounds and Mixtures","The Amazing World of Solutes, Solvents and Solutions","Light: Mirrors and Lenses","Keeping Time with the Skies","How Nature Works in Harmony","Our Home: Earth - A Unique Life Sustaining Planet"]],
["name"=>"English Grammar","topics"=>["Nouns (Kinds and Usage)","Pronouns and Their Types","Determiners and Articles","Adjectives and Degrees of Comparison","Verbs (Transitive and Intransitive)","Subject-Verb Agreement","Tenses (Present, Past, Future)","Perfect and Continuous Tenses","Modals","Adverbs","Prepositions","Conjunctions","Interjections","Active and Passive Voice","Direct and Indirect Speech","Punctuation","Kinds of Sentences","Sentence Transformation","Phrases and Clauses","Reported Speech","Synonyms and Antonyms","Idioms and Phrases","Vocabulary Building","Paragraph Writing","Letter Writing (Formal and Informal)","Notice Writing","Message Writing","Story Writing","Essay Writing","Comprehension (Unseen Passage)"]],
["name"=>"Social Science","topics"=>["Natural Resources and Their Use","Reshaping India's Political Map","The Rise of the Marathas","The Colonial Era in India","Universal Franchise and India's Electoral System","The Parliamentary System: Legislature and Executive","Factors of Production"]],
]],
["class"=>"Class 9","subjects"=>[
["name"=>"Maths","topics"=>["Uses of Coordinates","Number Systems","Polynomials","Linear Equations in Two Variables","Introduction to Euclid's Geometry","Lines and Angles","Triangles","Quadrilaterals","Areas of Parallelograms and Triangles","Circles","Constructions","Heron's Formula","Surface Areas and Volumes","Statistics","Probability"]],
["name"=>"Science","topics"=>["Exploration: Entering the World of Secondary Science","Cell: The Building Block of Life","Tissues in Action","Describing Motion Around Us","Exploring Mixtures and their Separation","How Forces Affect Motion","Work, Energy and Simple Machines","Journey Inside the Atom","Atomic Foundations of Matter","Sound Waves: Characteristics and Applications","Reproduction: How Life Continues","Patterns in Life: Diversity and Classification","Earth as a System: Energy, Matter, and Life"]],
["name"=>"English Grammar","topics"=>["Tenses (Present, Past, Future)","Modals","Subject-Verb Agreement","Determiners","Articles","Prepositions","Conjunctions","Adverbs","Active and Passive Voice","Direct and Indirect Speech","Clauses (Noun, Adjective, Adverb Clauses)","Phrases","Sentence Transformation","Reported Speech","Editing and Omission","Rearrangement of Sentences","Gap Filling","Error Correction","Punctuation","Synonyms and Antonyms","Idioms and Phrases","Vocabulary Building","Paragraph Writing","Story Writing","Article Writing","Letter Writing (Formal and Informal)","Speech Writing","Diary Entry","Comprehension (Unseen Passage)"]],
["name"=>"Social Science","topics"=>["Social Science: Meaning, Scope and Importance","India: Size, Location and Physical Features","Climate and Natural Vegetation","Population and Human Resources","Understanding History: Sources and Timeline","Ancient Civilisations and Their Legacy","Medieval India: Society and Culture","Colonialism and Its Impact","Democracy: Meaning and Features","The Constitution of India","Electoral Politics and Governance","Economic Activities: Production and Distribution","Poverty, Inequality and Development","Natural Resources and Sustainable Development"]],
]],
["class"=>"Class 10","subjects"=>[
["name"=>"Maths","topics"=>["Real Numbers","Polynomials","Pair of Linear Equations in Two Variables","Quadratic Equations","Arithmetic Progressions","Triangles","Coordinate Geometry","Trigonometric Identities","Heights and Distances","Circles","Constructions","Areas Related to Circles","Surface Areas and Volumes","Statistics","Probability"]],
["name"=>"Science","topics"=>["Chemical Reactions and Equations","Acids, Bases and Salts","Metals and Non-metals","Carbon and Its Compounds","Periodic Classification of Elements","Life Processes","Control and Coordination","How Do Organisms Reproduce","Heredity and Evolution","Light - Reflection and Refraction","The Human Eye and the Colourful World","Electricity","Magnetic Effects of Electric Current","Sources of Energy","Our Environment","Management of Natural Resources"]],
["name"=>"English Grammar","topics"=>["Tenses","Modals","Subject-Verb Agreement","Determiners","Articles","Prepositions","Conjunctions","Adverbs","Active and Passive Voice","Direct and Indirect Speech","Clauses (Noun, Adjective, Adverb Clauses)","Phrases","Sentence Transformation","Editing and Omission","Rearrangement of Sentences","Gap Filling","Error Correction","Reported Speech","Punctuation","Synonyms and Antonyms","Idioms and Phrases","Vocabulary Building","Formal Letter Writing","Letter to the Editor","Article Writing","Speech Writing","Report Writing","Analytical Paragraph Writing","Story Writing","Comprehension (Unseen Passage)"]],
["name"=>"Social Science","topics"=>["The Rise of Nationalism in Europe","Nationalism in India","The Making of a Global World","The Age of Industrialisation","Print Culture and the Modern World","Resources and Development","Forest and Wildlife Resources","Water Resources","Agriculture","Minerals and Energy Resources","Manufacturing Industries","Lifelines of National Economy","Power Sharing","Federalism","Gender, Religion and Caste","Political Parties","Outcomes of Democracy","Challenges to Democracy","Development","Sectors of the Indian Economy","Money and Credit","Globalisation and the Indian Economy","Consumer Rights"]],
]],
];

$out = "-- HeyyGuru: Complete Syllabus Data (Class 1-10) - Updated " . date('Y-m-d') . "\n";
$out .= "-- WARNING: This will DELETE all existing syllabus data and re-insert\n\n";
$out .= "DELETE FROM syllabus;\n\n";
$out .= "INSERT INTO syllabus (class, subject, topic, status) VALUES\n";

$rows = [];
foreach ($classes as $cls) {
    foreach ($cls['subjects'] as $subj) {
        foreach ($subj['topics'] as $topic) {
            $c = addslashes($cls['class']);
            $s = addslashes($subj['name']);
            $t = addslashes($topic);
            $rows[] = "('$c', '$s', '$t', 'Pending')";
        }
    }
}
$out .= implode(",\n", $rows) . ";\n";

file_put_contents(__DIR__ . '/syllabus_data_updated.sql', $out);
echo "Generated " . count($rows) . " rows\n";
