-- HeyyGuru: Complete Syllabus Data (Class 1-10) - Updated 2026-05-04
-- WARNING: This will DELETE all existing syllabus data and re-insert

DELETE FROM syllabus;

INSERT INTO syllabus (class, subject, topic, status) VALUES
('Class 1', 'Maths', 'Pre-Number Concepts', 'Pending'),
('Class 1', 'Maths', 'Numbers 1-100', 'Pending'),
('Class 1', 'Maths', 'Place Value (Tens and Ones)', 'Pending'),
('Class 1', 'Maths', 'Comparison of Numbers', 'Pending'),
('Class 1', 'Maths', 'Addition', 'Pending'),
('Class 1', 'Maths', 'Subtraction', 'Pending'),
('Class 1', 'Maths', 'Introduction to Multiplication (Repeated Addition)', 'Pending'),
('Class 1', 'Maths', 'Introduction to Division (Equal Sharing)', 'Pending'),
('Class 1', 'Maths', 'Shapes (2D and 3D)', 'Pending'),
('Class 1', 'Maths', 'Patterns', 'Pending'),
('Class 1', 'Maths', 'Measurement (Length, Weight, Capacity)', 'Pending'),
('Class 1', 'Maths', 'Time (Days, Months, O\'Clock)', 'Pending'),
('Class 1', 'Maths', 'Money', 'Pending'),
('Class 1', 'Maths', 'Data Handling (Picture Graphs)', 'Pending'),
('Class 1', 'Maths', 'Spatial Understanding', 'Pending'),
('Class 1', 'Maths', 'Applied Mathematics (Daily Life Maths)', 'Pending'),
('Class 1', 'English Grammar', 'Alphabet (Capital and Small Letters)', 'Pending'),
('Class 1', 'English Grammar', 'Vowels and Consonants', 'Pending'),
('Class 1', 'English Grammar', 'Phonics and Letter Sounds', 'Pending'),
('Class 1', 'English Grammar', 'Blending and Word Formation', 'Pending'),
('Class 1', 'English Grammar', 'Naming Words (Nouns)', 'Pending'),
('Class 1', 'English Grammar', 'Common and Proper Nouns (Basic Introduction)', 'Pending'),
('Class 1', 'English Grammar', 'One and Many (Singular and Plural)', 'Pending'),
('Class 1', 'English Grammar', 'Gender (He/She)', 'Pending'),
('Class 1', 'English Grammar', 'Use of A and An', 'Pending'),
('Class 1', 'English Grammar', 'This and That', 'Pending'),
('Class 1', 'English Grammar', 'These and Those', 'Pending'),
('Class 1', 'English Grammar', 'Pronouns (He, She, It, They)', 'Pending'),
('Class 1', 'English Grammar', 'Describing Words (Adjectives)', 'Pending'),
('Class 1', 'English Grammar', 'Action Words (Verbs)', 'Pending'),
('Class 1', 'English Grammar', 'Is, Am, Are', 'Pending'),
('Class 1', 'English Grammar', 'Has and Have', 'Pending'),
('Class 1', 'English Grammar', 'Simple Present Tense', 'Pending'),
('Class 1', 'English Grammar', 'Sentence Formation', 'Pending'),
('Class 1', 'English Grammar', 'Capital Letter and Full Stop', 'Pending'),
('Class 1', 'English Grammar', 'Question Words (What, Where, Who)', 'Pending'),
('Class 1', 'English Grammar', 'Prepositions (In, On, Under, Behind)', 'Pending'),
('Class 1', 'English Grammar', 'Joining Words (And)', 'Pending'),
('Class 1', 'English Grammar', 'Opposites', 'Pending'),
('Class 1', 'English Grammar', 'Rhyming Words', 'Pending'),
('Class 1', 'English Grammar', 'Picture Composition (Oral)', 'Pending'),
('Class 1', 'English Grammar', 'Reading Simple Sentences', 'Pending'),
('Class 1', 'English Grammar', 'Listening and Speaking Skills', 'Pending'),
('Class 1', 'EVS', 'Our Universe', 'Pending'),
('Class 1', 'EVS', 'Myself and My Body', 'Pending'),
('Class 1', 'EVS', 'Plants and Animals', 'Pending'),
('Class 1', 'EVS', 'Our Family', 'Pending'),
('Class 1', 'EVS', 'Our Neighbourhood', 'Pending'),
('Class 1', 'EVS', 'Weather, Air and Water', 'Pending'),
('Class 1', 'EVS', 'Transport and Communication', 'Pending'),
('Class 1', 'EVS', 'Means of Communication', 'Pending'),
('Class 1', 'EVS', 'Occasions and Festivals', 'Pending'),
('Class 1', 'EVS', 'Our Environment', 'Pending'),
('Class 1', 'EVS', 'Living and Non-Living Things', 'Pending'),
('Class 1', 'EVS', 'Types of Materials', 'Pending'),
('Class 1', 'EVS', 'Uses of Materials', 'Pending'),
('Class 1', 'EVS', 'Safety and Good Habits', 'Pending'),
('Class 1', 'EVS', 'Food We Eat', 'Pending'),
('Class 1', 'EVS', 'Clothes We Wear', 'Pending'),
('Class 1', 'EVS', 'Houses We Live In', 'Pending'),
('Class 1', 'EVS', 'Seasons', 'Pending'),
('Class 1', 'EVS', 'Occupations and Community Helpers', 'Pending'),
('Class 1', 'EVS', 'Famous Personalities of India', 'Pending'),
('Class 1', 'EVS', 'Natural Resources', 'Pending'),
('Class 1', 'EVS', 'Pollution and Conservation', 'Pending'),
('Class 1', 'EVS', 'Good Touch and Bad Touch (Basic Awareness)', 'Pending'),
('Class 1', 'EVS', 'Road Safety Rules', 'Pending'),
('Class 1', 'EVS', 'Reduce, Reuse, Recycle', 'Pending'),
('Class 1', 'Social Science', 'Ourself and Our Family', 'Pending'),
('Class 1', 'Social Science', 'Our Neighbourhood', 'Pending'),
('Class 1', 'Social Science', 'My School and Community', 'Pending'),
('Class 1', 'Social Science', 'Rules and Responsibilities', 'Pending'),
('Class 1', 'Social Science', 'Good Citizenship', 'Pending'),
('Class 1', 'Social Science', 'National Symbols of India', 'Pending'),
('Class 1', 'Social Science', 'Our Country India (Basic Introduction)', 'Pending'),
('Class 1', 'Social Science', 'States and Capitals (Basic Awareness)', 'Pending'),
('Class 1', 'Social Science', 'Land and Water Forms', 'Pending'),
('Class 1', 'Social Science', 'Directions (North, South, East, West)', 'Pending'),
('Class 1', 'Social Science', 'Weather and Seasons', 'Pending'),
('Class 1', 'Social Science', 'Transport', 'Pending'),
('Class 1', 'Social Science', 'Communication', 'Pending'),
('Class 1', 'Social Science', 'Occupations and Community Helpers', 'Pending'),
('Class 1', 'Social Science', 'Festivals of India', 'Pending'),
('Class 1', 'Social Science', 'Famous Indian Leaders', 'Pending'),
('Class 1', 'Social Science', 'Maps and Globes (Basic Introduction)', 'Pending'),
('Class 1', 'Social Science', 'Safety Rules (Home and Road)', 'Pending'),
('Class 1', 'Social Science', 'Our Environment', 'Pending'),
('Class 1', 'Social Science', 'Caring for Public Property', 'Pending'),
('Class 2', 'Maths', 'Revision of Numbers up to 100', 'Pending'),
('Class 2', 'Maths', 'Numbers up to 1000', 'Pending'),
('Class 2', 'Maths', 'Place Value (Hundreds, Tens and Ones)', 'Pending'),
('Class 2', 'Maths', 'Expanded and Short Form', 'Pending'),
('Class 2', 'Maths', 'Comparison of Numbers', 'Pending'),
('Class 2', 'Maths', 'Ascending and Descending Order', 'Pending'),
('Class 2', 'Maths', 'Addition (2 and 3 Digit)', 'Pending'),
('Class 2', 'Maths', 'Subtraction (With and Without Borrowing)', 'Pending'),
('Class 2', 'Maths', 'Multiplication (Repeated Addition and Tables 2-10)', 'Pending'),
('Class 2', 'Maths', 'Division (Equal Sharing and Grouping)', 'Pending'),
('Class 2', 'Maths', 'Odd and Even Numbers', 'Pending'),
('Class 2', 'Maths', 'Ordinal Numbers', 'Pending'),
('Class 2', 'Maths', 'Fractions (Half, One-Third, One-Fourth)', 'Pending'),
('Class 2', 'Maths', 'Measurement of Length', 'Pending'),
('Class 2', 'Maths', 'Measurement of Weight', 'Pending'),
('Class 2', 'Maths', 'Measurement of Capacity', 'Pending'),
('Class 2', 'Maths', 'Time (Clock, Calendar)', 'Pending'),
('Class 2', 'Maths', 'Money (Addition and Subtraction of Money)', 'Pending'),
('Class 2', 'Maths', 'Shapes (2D and 3D)', 'Pending'),
('Class 2', 'Maths', 'Patterns', 'Pending'),
('Class 2', 'Maths', 'Data Handling (Pictographs and Tally Marks)', 'Pending'),
('Class 2', 'Maths', 'Basic Geometry (Lines and Curves)', 'Pending'),
('Class 2', 'Maths', 'Spatial Understanding', 'Pending'),
('Class 2', 'Maths', 'Word Problems (Daily Life Maths)', 'Pending'),
('Class 2', 'Maths', 'Mental Mathematics', 'Pending'),
('Class 2', 'English Grammar', 'Alphabetical Order', 'Pending'),
('Class 2', 'English Grammar', 'Vowels and Consonants', 'Pending'),
('Class 2', 'English Grammar', 'Phonics and Blends', 'Pending'),
('Class 2', 'English Grammar', 'Nouns (Naming Words)', 'Pending'),
('Class 2', 'English Grammar', 'Common and Proper Nouns', 'Pending'),
('Class 2', 'English Grammar', 'Singular and Plural', 'Pending'),
('Class 2', 'English Grammar', 'Gender (Masculine and Feminine)', 'Pending'),
('Class 2', 'English Grammar', 'Pronouns', 'Pending'),
('Class 2', 'English Grammar', 'Adjectives (Describing Words)', 'Pending'),
('Class 2', 'English Grammar', 'Verbs (Action Words)', 'Pending'),
('Class 2', 'English Grammar', 'Is, Am, Are', 'Pending'),
('Class 2', 'English Grammar', 'Was and Were (Basic)', 'Pending'),
('Class 2', 'English Grammar', 'Has and Have', 'Pending'),
('Class 2', 'English Grammar', 'Simple Present Tense', 'Pending'),
('Class 2', 'English Grammar', 'Simple Past Tense (Basic)', 'Pending'),
('Class 2', 'English Grammar', 'Articles (A, An, The)', 'Pending'),
('Class 2', 'English Grammar', 'Prepositions (In, On, Under, Behind, Between)', 'Pending'),
('Class 2', 'English Grammar', 'Conjunctions (And, But)', 'Pending'),
('Class 2', 'English Grammar', 'Adverbs (Basic Introduction)', 'Pending'),
('Class 2', 'English Grammar', 'Sentence Formation', 'Pending'),
('Class 2', 'English Grammar', 'Kinds of Sentences (Statement, Question, Command, Exclamation)', 'Pending'),
('Class 2', 'English Grammar', 'Capital Letters and Punctuation', 'Pending'),
('Class 2', 'English Grammar', 'Question Words (Who, What, When, Where, Why, How)', 'Pending'),
('Class 2', 'English Grammar', 'Opposites', 'Pending'),
('Class 2', 'English Grammar', 'Synonyms (Basic)', 'Pending'),
('Class 2', 'English Grammar', 'Homophones (Basic)', 'Pending'),
('Class 2', 'English Grammar', 'Paragraph Writing (Guided)', 'Pending'),
('Class 2', 'English Grammar', 'Picture Composition', 'Pending'),
('Class 2', 'English Grammar', 'Comprehension (Unseen Passage)', 'Pending'),
('Class 2', 'English Grammar', 'Listening and Speaking Skills', 'Pending'),
('Class 2', 'EVS', 'Myself and My Family', 'Pending'),
('Class 2', 'EVS', 'Our Body and Healthy Habits', 'Pending'),
('Class 2', 'EVS', 'Food We Eat', 'Pending'),
('Class 2', 'EVS', 'Clothes We Wear', 'Pending'),
('Class 2', 'EVS', 'Houses We Live In', 'Pending'),
('Class 2', 'EVS', 'Our Neighbourhood', 'Pending'),
('Class 2', 'EVS', 'People Who Help Us (Community Helpers)', 'Pending'),
('Class 2', 'EVS', 'Transport and Communication', 'Pending'),
('Class 2', 'EVS', 'Means of Communication', 'Pending'),
('Class 2', 'EVS', 'Plants Around Us', 'Pending'),
('Class 2', 'EVS', 'Uses of Plants', 'Pending'),
('Class 2', 'EVS', 'Animals Around Us', 'Pending'),
('Class 2', 'EVS', 'Wild and Domestic Animals', 'Pending'),
('Class 2', 'EVS', 'Living and Non-Living Things', 'Pending'),
('Class 2', 'EVS', 'Air, Water and Weather', 'Pending'),
('Class 2', 'EVS', 'Seasons', 'Pending'),
('Class 2', 'EVS', 'Sources of Water', 'Pending'),
('Class 2', 'EVS', 'Uses of Water and Water Conservation', 'Pending'),
('Class 2', 'EVS', 'Types of Materials', 'Pending'),
('Class 2', 'EVS', 'Uses of Materials', 'Pending'),
('Class 2', 'EVS', 'Safety Rules (Home and Road)', 'Pending'),
('Class 2', 'EVS', 'Festivals of India', 'Pending'),
('Class 2', 'EVS', 'Occupations', 'Pending'),
('Class 2', 'EVS', 'Our Environment and Cleanliness', 'Pending'),
('Class 2', 'EVS', 'Reduce, Reuse and Recycle', 'Pending'),
('Class 2', 'EVS', 'Simple Machines (Basic Introduction)', 'Pending'),
('Class 2', 'EVS', 'Solar System (Basic Awareness)', 'Pending'),
('Class 2', 'Social Science', 'Myself and My Family', 'Pending'),
('Class 2', 'Social Science', 'Our Neighbourhood', 'Pending'),
('Class 2', 'Social Science', 'My School and Community', 'Pending'),
('Class 2', 'Social Science', 'Rules and Responsibilities', 'Pending'),
('Class 2', 'Social Science', 'Good Manners and Good Citizenship', 'Pending'),
('Class 2', 'Social Science', 'National Symbols of India', 'Pending'),
('Class 2', 'Social Science', 'Our Country India (Basic Introduction)', 'Pending'),
('Class 2', 'Social Science', 'States and Capitals (Basic Awareness)', 'Pending'),
('Class 2', 'Social Science', 'Directions (North, South, East, West)', 'Pending'),
('Class 2', 'Social Science', 'Maps and Globe (Basic Introduction)', 'Pending'),
('Class 2', 'Social Science', 'Landforms (Mountains, Plains, Rivers, Deserts)', 'Pending'),
('Class 2', 'Social Science', 'Weather and Seasons', 'Pending'),
('Class 2', 'Social Science', 'Transport', 'Pending'),
('Class 2', 'Social Science', 'Communication', 'Pending'),
('Class 2', 'Social Science', 'Occupations and Community Helpers', 'Pending'),
('Class 2', 'Social Science', 'Festivals of India', 'Pending'),
('Class 2', 'Social Science', 'Famous Indian Leaders and Personalities', 'Pending'),
('Class 2', 'Social Science', 'Safety Rules (Home, School and Road)', 'Pending'),
('Class 2', 'Social Science', 'Caring for Public Property', 'Pending'),
('Class 2', 'Social Science', 'Our Environment and Natural Resources', 'Pending'),
('Class 3', 'Maths', 'Number System (4-5 Digit Numbers)', 'Pending'),
('Class 3', 'Maths', 'Place Value and Face Value', 'Pending'),
('Class 3', 'Maths', 'Expanded Form and Short Form', 'Pending'),
('Class 3', 'Maths', 'Comparison and Ordering of Numbers', 'Pending'),
('Class 3', 'Maths', 'Roman Numerals (I-L)', 'Pending'),
('Class 3', 'Maths', 'Addition (4 Digit)', 'Pending'),
('Class 3', 'Maths', 'Subtraction (With and Without Borrowing)', 'Pending'),
('Class 3', 'Maths', 'Multiplication (2 and 3 Digit by 1 Digit)', 'Pending'),
('Class 3', 'Maths', 'Division (Basic Long Division)', 'Pending'),
('Class 3', 'Maths', 'Properties of Multiplication', 'Pending'),
('Class 3', 'Maths', 'Fractions (Like Fractions and Comparison)', 'Pending'),
('Class 3', 'Maths', 'Introduction to Geometry', 'Pending'),
('Class 3', 'Maths', 'Lines (Straight, Curved, Parallel, Intersecting)', 'Pending'),
('Class 3', 'Maths', '2D and 3D Shapes', 'Pending'),
('Class 3', 'Maths', 'Patterns and Symmetry', 'Pending'),
('Class 3', 'Maths', 'Measurement of Length', 'Pending'),
('Class 3', 'Maths', 'Measurement of Weight', 'Pending'),
('Class 3', 'Maths', 'Measurement of Capacity', 'Pending'),
('Class 3', 'Maths', 'Perimeter (Basic Introduction)', 'Pending'),
('Class 3', 'Maths', 'Area (Counting Squares Method)', 'Pending'),
('Class 3', 'Maths', 'Time (Clock and Calendar)', 'Pending'),
('Class 3', 'Maths', 'Money (Bills and Word Problems)', 'Pending'),
('Class 3', 'Maths', 'Data Handling (Pictographs and Bar Graphs)', 'Pending'),
('Class 3', 'Maths', 'Mental Mathematics', 'Pending'),
('Class 3', 'Maths', 'Word Problems (Daily Life Applications)', 'Pending'),
('Class 3', 'English Grammar', 'Alphabetical Order and Dictionary Skills', 'Pending'),
('Class 3', 'English Grammar', 'Nouns (Common, Proper and Collective)', 'Pending'),
('Class 3', 'English Grammar', 'Countable and Uncountable Nouns', 'Pending'),
('Class 3', 'English Grammar', 'Singular and Plural', 'Pending'),
('Class 3', 'English Grammar', 'Gender', 'Pending'),
('Class 3', 'English Grammar', 'Pronouns (Personal and Possessive)', 'Pending'),
('Class 3', 'English Grammar', 'Adjectives (Quality, Quantity and Number)', 'Pending'),
('Class 3', 'English Grammar', 'Comparison of Adjectives', 'Pending'),
('Class 3', 'English Grammar', 'Articles (A, An, The)', 'Pending'),
('Class 3', 'English Grammar', 'Verbs (Action and Helping Verbs)', 'Pending'),
('Class 3', 'English Grammar', 'Subject-Verb Agreement (Basic)', 'Pending'),
('Class 3', 'English Grammar', 'Simple Present Tense', 'Pending'),
('Class 3', 'English Grammar', 'Simple Past Tense', 'Pending'),
('Class 3', 'English Grammar', 'Simple Future Tense (Basic)', 'Pending'),
('Class 3', 'English Grammar', 'Adverbs (Introduction)', 'Pending'),
('Class 3', 'English Grammar', 'Prepositions', 'Pending'),
('Class 3', 'English Grammar', 'Conjunctions (And, But, Or)', 'Pending'),
('Class 3', 'English Grammar', 'Interjections', 'Pending'),
('Class 3', 'English Grammar', 'Kinds of Sentences', 'Pending'),
('Class 3', 'English Grammar', 'Sentence Formation and Word Order', 'Pending'),
('Class 3', 'English Grammar', 'Negative Sentences', 'Pending'),
('Class 3', 'English Grammar', 'Interrogative Sentences', 'Pending'),
('Class 3', 'English Grammar', 'Punctuation (Capital Letters, Full Stop, Comma, Question Mark, Exclamation Mark)', 'Pending'),
('Class 3', 'English Grammar', 'Opposites and Synonyms', 'Pending'),
('Class 3', 'English Grammar', 'Homophones (Basic)', 'Pending'),
('Class 3', 'English Grammar', 'Idioms (Basic Introduction)', 'Pending'),
('Class 3', 'English Grammar', 'Paragraph Writing', 'Pending'),
('Class 3', 'English Grammar', 'Letter Writing (Informal)', 'Pending'),
('Class 3', 'English Grammar', 'Comprehension (Unseen Passage)', 'Pending'),
('Class 3', 'English Grammar', 'Picture Composition', 'Pending'),
('Class 3', 'English Grammar', 'Listening and Speaking Skills', 'Pending'),
('Class 3', 'EVS', 'Our Universe', 'Pending'),
('Class 3', 'EVS', 'The Solar System', 'Pending'),
('Class 3', 'EVS', 'The Earth and Its Features', 'Pending'),
('Class 3', 'EVS', 'Measurement (Basic Scientific Measurement)', 'Pending'),
('Class 3', 'EVS', 'Soil and Its Types', 'Pending'),
('Class 3', 'EVS', 'Our Environment', 'Pending'),
('Class 3', 'EVS', 'Living and Non-Living Things', 'Pending'),
('Class 3', 'EVS', 'Plants Around Us', 'Pending'),
('Class 3', 'EVS', 'Animals Around Us', 'Pending'),
('Class 3', 'EVS', 'Birds and Their Bodies', 'Pending'),
('Class 3', 'EVS', 'Human Body (Organs and Organ Systems)', 'Pending'),
('Class 3', 'EVS', 'Safety and First Aid', 'Pending'),
('Class 3', 'EVS', 'States of Matter (Solid, Liquid and Gas)', 'Pending'),
('Class 3', 'EVS', 'Housing and Clothing', 'Pending'),
('Class 3', 'EVS', 'Materials Around Us (What Things Are Made Of)', 'Pending'),
('Class 3', 'EVS', 'Light and Sound', 'Pending'),
('Class 3', 'EVS', 'Air and Water', 'Pending'),
('Class 3', 'EVS', 'Weather and Seasons', 'Pending'),
('Class 3', 'EVS', 'Sources of Energy (How Things Work)', 'Pending'),
('Class 3', 'EVS', 'Journey of a River', 'Pending'),
('Class 3', 'EVS', 'Natural Resources and Conservation', 'Pending'),
('Class 3', 'EVS', 'Our Vibrant Country (India - Physical and Cultural Features)', 'Pending'),
('Class 3', 'EVS', 'Some Unique Places of India', 'Pending'),
('Class 3', 'EVS', 'Pollution and Its Control', 'Pending'),
('Class 3', 'EVS', 'Food and Digestion (Basic Introduction)', 'Pending'),
('Class 3', 'EVS', 'Simple Machines (Basic Introduction)', 'Pending'),
('Class 3', 'EVS', 'Reduce, Reuse and Recycle', 'Pending'),
('Class 3', 'Social Science', 'My Family and I', 'Pending'),
('Class 3', 'Social Science', 'Our Neighbourhood and Community', 'Pending'),
('Class 3', 'Social Science', 'Our School and Responsibilities', 'Pending'),
('Class 3', 'Social Science', 'Good Citizenship and Civic Sense', 'Pending'),
('Class 3', 'Social Science', 'India - Our Country', 'Pending'),
('Class 3', 'Social Science', 'States and Union Territories', 'Pending'),
('Class 3', 'Social Science', 'National Symbols of India', 'Pending'),
('Class 3', 'Social Science', 'Physical Features of India', 'Pending'),
('Class 3', 'Social Science', 'Maps and Directions', 'Pending'),
('Class 3', 'Social Science', 'Globe and the Earth', 'Pending'),
('Class 3', 'Social Science', 'Landforms (Mountains, Plains, Plateaus, Deserts, Islands)', 'Pending'),
('Class 3', 'Social Science', 'Water Bodies (Rivers, Seas, Oceans)', 'Pending'),
('Class 3', 'Social Science', 'Weather and Climate', 'Pending'),
('Class 3', 'Social Science', 'Natural Resources', 'Pending'),
('Class 3', 'Social Science', 'Transport and Communication', 'Pending'),
('Class 3', 'Social Science', 'Occupations and Industries (Basic Introduction)', 'Pending'),
('Class 3', 'Social Science', 'Rural and Urban Life', 'Pending'),
('Class 3', 'Social Science', 'Festivals and Cultural Diversity of India', 'Pending'),
('Class 3', 'Social Science', 'Famous Indian Leaders and Personalities', 'Pending'),
('Class 3', 'Social Science', 'Monuments and Heritage Sites', 'Pending'),
('Class 3', 'Social Science', 'Safety and Disaster Management (Basic)', 'Pending'),
('Class 3', 'Social Science', 'Caring for the Environment', 'Pending'),
('Class 3', 'Social Science', 'Local Government (Basic Introduction)', 'Pending'),
('Class 3', 'Social Science', 'Journey of a River', 'Pending'),
('Class 3', 'Social Science', 'Our Rights and Duties (Basic Introduction)', 'Pending'),
('Class 4', 'Maths', 'Building with Bricks', 'Pending'),
('Class 4', 'Maths', 'Long and Short', 'Pending'),
('Class 4', 'Maths', 'A Trip to Bhopal', 'Pending'),
('Class 4', 'Maths', 'Tick Tick Tick (Time)', 'Pending'),
('Class 4', 'Maths', 'The Way the World Looks (Shapes and Mapping)', 'Pending'),
('Class 4', 'Maths', 'The Junk Seller (Money)', 'Pending'),
('Class 4', 'Maths', 'Jugs and Mugs (Capacity)', 'Pending'),
('Class 4', 'Maths', 'Carts and Wheels (Multiplication)', 'Pending'),
('Class 4', 'Maths', 'Numbers (Large Numbers and Place Value)', 'Pending'),
('Class 4', 'Maths', 'Addition and Subtraction', 'Pending'),
('Class 4', 'Maths', 'Multiplication', 'Pending'),
('Class 4', 'Maths', 'Division', 'Pending'),
('Class 4', 'Maths', 'Factors and Multiples', 'Pending'),
('Class 4', 'Maths', 'LCM and HCF', 'Pending'),
('Class 4', 'Maths', 'Fractions', 'Pending'),
('Class 4', 'Maths', 'Decimals', 'Pending'),
('Class 4', 'Maths', 'Time', 'Pending'),
('Class 4', 'Maths', 'Geometry (Lines, Angles and Shapes)', 'Pending'),
('Class 4', 'Maths', 'Measurement (Length, Weight and Capacity)', 'Pending'),
('Class 4', 'Maths', 'Perimeter', 'Pending'),
('Class 4', 'Maths', 'Money', 'Pending'),
('Class 4', 'Maths', 'Symmetry and Patterns', 'Pending'),
('Class 4', 'Maths', 'Data Handling / Pictograph', 'Pending'),
('Class 4', 'English Grammar', 'Nouns (Common, Proper, Collective, Abstract)', 'Pending'),
('Class 4', 'English Grammar', 'Countable and Uncountable Nouns', 'Pending'),
('Class 4', 'English Grammar', 'Singular and Plural', 'Pending'),
('Class 4', 'English Grammar', 'Gender', 'Pending'),
('Class 4', 'English Grammar', 'Pronouns (Personal, Possessive, Reflexive)', 'Pending'),
('Class 4', 'English Grammar', 'Adjectives (Quality, Quantity, Number)', 'Pending'),
('Class 4', 'English Grammar', 'Degrees of Comparison', 'Pending'),
('Class 4', 'English Grammar', 'Articles (A, An, The)', 'Pending'),
('Class 4', 'English Grammar', 'Verbs (Main and Helping Verbs)', 'Pending'),
('Class 4', 'English Grammar', 'Subject-Verb Agreement', 'Pending'),
('Class 4', 'English Grammar', 'Simple Present Tense', 'Pending'),
('Class 4', 'English Grammar', 'Simple Past Tense', 'Pending'),
('Class 4', 'English Grammar', 'Simple Future Tense', 'Pending'),
('Class 4', 'English Grammar', 'Present Continuous Tense', 'Pending'),
('Class 4', 'English Grammar', 'Past Continuous Tense (Basic)', 'Pending'),
('Class 4', 'English Grammar', 'Adverbs', 'Pending'),
('Class 4', 'English Grammar', 'Prepositions', 'Pending'),
('Class 4', 'English Grammar', 'Conjunctions', 'Pending'),
('Class 4', 'English Grammar', 'Interjections', 'Pending'),
('Class 4', 'English Grammar', 'Kinds of Sentences', 'Pending'),
('Class 4', 'English Grammar', 'Negative and Interrogative Sentences', 'Pending'),
('Class 4', 'English Grammar', 'Active and Passive Voice (Basic Introduction)', 'Pending'),
('Class 4', 'English Grammar', 'Direct and Indirect Speech (Basic)', 'Pending'),
('Class 4', 'English Grammar', 'Punctuation (Comma, Apostrophe, Quotation Marks)', 'Pending'),
('Class 4', 'English Grammar', 'Synonyms and Antonyms', 'Pending'),
('Class 4', 'English Grammar', 'Homophones', 'Pending'),
('Class 4', 'English Grammar', 'Idioms and Proverbs (Basic)', 'Pending'),
('Class 4', 'English Grammar', 'Paragraph Writing', 'Pending'),
('Class 4', 'English Grammar', 'Letter Writing (Informal and Formal - Basic)', 'Pending'),
('Class 4', 'English Grammar', 'Comprehension (Unseen Passage)', 'Pending'),
('Class 4', 'English Grammar', 'Story Writing', 'Pending'),
('Class 4', 'English Grammar', 'Picture Composition', 'Pending'),
('Class 4', 'English Grammar', 'Listening and Speaking Skills', 'Pending'),
('Class 4', 'EVS', 'Going to School (Transport and Safety)', 'Pending'),
('Class 4', 'EVS', 'Food for Plants (Photosynthesis - Basic Introduction)', 'Pending'),
('Class 4', 'EVS', 'States of Matter (Solid, Liquid and Gas)', 'Pending'),
('Class 4', 'EVS', 'Force and Energy', 'Pending'),
('Class 4', 'EVS', 'Adaptations in Plants', 'Pending'),
('Class 4', 'EVS', 'Adaptations in Animals', 'Pending'),
('Class 4', 'EVS', 'Clothes We Wear', 'Pending'),
('Class 4', 'EVS', 'Food - Our Basic Need', 'Pending'),
('Class 4', 'EVS', 'Teeth and the Digestive System', 'Pending'),
('Class 4', 'EVS', 'Circulatory and Respiratory Systems', 'Pending'),
('Class 4', 'EVS', 'Fibre and Fabric', 'Pending'),
('Class 4', 'EVS', 'The Solar System and Types of Planets', 'Pending'),
('Class 4', 'EVS', 'The Earth and the Sky', 'Pending'),
('Class 4', 'EVS', 'Natural Resources', 'Pending'),
('Class 4', 'EVS', 'Forests and Wildlife', 'Pending'),
('Class 4', 'EVS', 'Water and Its Conservation', 'Pending'),
('Class 4', 'EVS', 'Air and Pollution', 'Pending'),
('Class 4', 'EVS', 'Soil and Its Types', 'Pending'),
('Class 4', 'EVS', 'Weather and Seasons', 'Pending'),
('Class 4', 'EVS', 'Simple Machines', 'Pending'),
('Class 4', 'EVS', 'Safety and First Aid', 'Pending'),
('Class 4', 'EVS', 'Our Environment and Conservation', 'Pending'),
('Class 4', 'Social Science', 'My Family and Community', 'Pending'),
('Class 4', 'Social Science', 'Our Society and Diversity', 'Pending'),
('Class 4', 'Social Science', 'India - Our Motherland', 'Pending'),
('Class 4', 'Social Science', 'States and Union Territories of India', 'Pending'),
('Class 4', 'Social Science', 'Physical Features of India', 'Pending'),
('Class 4', 'Social Science', 'The Northern Mountains', 'Pending'),
('Class 4', 'Social Science', 'The Northern Plains', 'Pending'),
('Class 4', 'Social Science', 'The Desert Region', 'Pending'),
('Class 4', 'Social Science', 'The Coastal Plains and Islands', 'Pending'),
('Class 4', 'Social Science', 'Climate of India', 'Pending'),
('Class 4', 'Social Science', 'Natural Vegetation and Wildlife', 'Pending'),
('Class 4', 'Social Science', 'Soil and Natural Resources', 'Pending'),
('Class 4', 'Social Science', 'Agriculture and Occupations', 'Pending'),
('Class 4', 'Social Science', 'Transport and Communication', 'Pending'),
('Class 4', 'Social Science', 'Our Government (Local Government - Panchayat and Municipality)', 'Pending'),
('Class 4', 'Social Science', 'Rights and Duties of Citizens', 'Pending'),
('Class 4', 'Social Science', 'National Symbols and National Leaders', 'Pending'),
('Class 4', 'Social Science', 'Our Cultural Heritage', 'Pending'),
('Class 4', 'Social Science', 'Famous Monuments of India', 'Pending'),
('Class 4', 'Social Science', 'Maps and Globes', 'Pending'),
('Class 4', 'Social Science', 'Latitudes and Longitudes (Basic Introduction)', 'Pending'),
('Class 4', 'Social Science', 'Disaster Management (Basic)', 'Pending'),
('Class 4', 'Social Science', 'Caring for the Environment', 'Pending'),
('Class 4', 'Social Science', 'Industries of India (Basic Introduction)', 'Pending'),
('Class 4', 'Social Science', 'Rural and Urban Administration', 'Pending'),
('Class 5', 'Maths', 'Large Numbers and Roman Numerals', 'Pending'),
('Class 5', 'Maths', 'Operations on Whole Numbers', 'Pending'),
('Class 5', 'Maths', 'Tests of Divisibility', 'Pending'),
('Class 5', 'Maths', 'Factors and Multiples', 'Pending'),
('Class 5', 'Maths', 'LCM and HCF', 'Pending'),
('Class 5', 'Maths', 'Fractions', 'Pending'),
('Class 5', 'Maths', 'Decimals', 'Pending'),
('Class 5', 'Maths', 'Ratio and Proportion', 'Pending'),
('Class 5', 'Maths', 'Measurement (Length, Weight and Capacity)', 'Pending'),
('Class 5', 'Maths', 'Time and Temperature', 'Pending'),
('Class 5', 'Maths', 'Mensuration', 'Pending'),
('Class 5', 'Maths', 'Perimeter and Area', 'Pending'),
('Class 5', 'Maths', 'Volume (Basic Introduction)', 'Pending'),
('Class 5', 'Maths', 'Geometry and Geometrical Figures', 'Pending'),
('Class 5', 'Maths', 'Angles and Lines', 'Pending'),
('Class 5', 'Maths', 'Data Handling (Bar Graph and Line Graph)', 'Pending'),
('Class 5', 'Maths', 'BODMAS Rule', 'Pending'),
('Class 5', 'Maths', 'Arithmetic Operations', 'Pending'),
('Class 5', 'Maths', 'Profit and Loss', 'Pending'),
('Class 5', 'Maths', 'Percentage', 'Pending'),
('Class 5', 'Maths', 'Average', 'Pending'),
('Class 5', 'Maths', 'Speed, Time and Distance', 'Pending'),
('Class 5', 'Maths', 'Unitary Method', 'Pending'),
('Class 5', 'Maths', 'Applied Mathematics (Word Problems and Daily Life Applications)', 'Pending'),
('Class 5', 'Maths', 'Mental Mathematics', 'Pending'),
('Class 5', 'English Grammar', 'Nouns (Common, Proper, Collective, Abstract)', 'Pending'),
('Class 5', 'English Grammar', 'Countable and Uncountable Nouns', 'Pending'),
('Class 5', 'English Grammar', 'Gender', 'Pending'),
('Class 5', 'English Grammar', 'Pronouns (Personal, Possessive, Reflexive, Demonstrative)', 'Pending'),
('Class 5', 'English Grammar', 'Adjectives and Degrees of Comparison', 'Pending'),
('Class 5', 'English Grammar', 'Articles (A, An, The)', 'Pending'),
('Class 5', 'English Grammar', 'Verbs (Main and Auxiliary)', 'Pending'),
('Class 5', 'English Grammar', 'Subject-Verb Agreement', 'Pending'),
('Class 5', 'English Grammar', 'Tenses (Simple Present, Past, Future)', 'Pending'),
('Class 5', 'English Grammar', 'Continuous Tenses (Present and Past)', 'Pending'),
('Class 5', 'English Grammar', 'Perfect Tense (Basic Introduction)', 'Pending'),
('Class 5', 'English Grammar', 'Adverbs (Manner, Time, Place)', 'Pending'),
('Class 5', 'English Grammar', 'Prepositions', 'Pending'),
('Class 5', 'English Grammar', 'Conjunctions', 'Pending'),
('Class 5', 'English Grammar', 'Interjections', 'Pending'),
('Class 5', 'English Grammar', 'Kinds of Sentences', 'Pending'),
('Class 5', 'English Grammar', 'Negative and Interrogative Sentences', 'Pending'),
('Class 5', 'English Grammar', 'Active and Passive Voice (Basic)', 'Pending'),
('Class 5', 'English Grammar', 'Direct and Indirect Speech (Basic)', 'Pending'),
('Class 5', 'English Grammar', 'Punctuation (Comma, Apostrophe, Quotation Marks, Colon)', 'Pending'),
('Class 5', 'English Grammar', 'Synonyms and Antonyms', 'Pending'),
('Class 5', 'English Grammar', 'Homophones and Homonyms', 'Pending'),
('Class 5', 'English Grammar', 'Idioms and Proverbs', 'Pending'),
('Class 5', 'English Grammar', 'Vocabulary Building', 'Pending'),
('Class 5', 'English Grammar', 'Paragraph Writing', 'Pending'),
('Class 5', 'English Grammar', 'Letter Writing (Formal and Informal)', 'Pending'),
('Class 5', 'English Grammar', 'Notice Writing (Basic)', 'Pending'),
('Class 5', 'English Grammar', 'Essay Writing', 'Pending'),
('Class 5', 'English Grammar', 'Story Writing', 'Pending'),
('Class 5', 'English Grammar', 'Comprehension (Unseen Passage)', 'Pending'),
('Class 5', 'English Grammar', 'Listening and Speaking Skills', 'Pending'),
('Class 5', 'EVS', 'Food - Where Does It Come From', 'Pending'),
('Class 5', 'EVS', 'Human Body (Skeletal and Muscular System)', 'Pending'),
('Class 5', 'EVS', 'The Nervous System', 'Pending'),
('Class 5', 'EVS', 'Work and Play (Health and Hygiene)', 'Pending'),
('Class 5', 'EVS', 'Plants Around Us', 'Pending'),
('Class 5', 'EVS', 'Reproduction in Plants', 'Pending'),
('Class 5', 'EVS', 'Ecosystem and Food Chain', 'Pending'),
('Class 5', 'EVS', 'Our Environment', 'Pending'),
('Class 5', 'EVS', 'Environmental Issues and Conservation', 'Pending'),
('Class 5', 'EVS', 'Pollution (Air, Water, Land and Noise)', 'Pending'),
('Class 5', 'EVS', 'Natural Calamities and Disaster Management', 'Pending'),
('Class 5', 'EVS', 'Safety and First Aid', 'Pending'),
('Class 5', 'EVS', 'The Solar System', 'Pending'),
('Class 5', 'EVS', 'Earth, Moon and Sun', 'Pending'),
('Class 5', 'EVS', 'Movement of the Earth and Seasons', 'Pending'),
('Class 5', 'EVS', 'Weather, Air and Water', 'Pending'),
('Class 5', 'EVS', 'Matter in Our Surroundings', 'Pending'),
('Class 5', 'EVS', 'Properties of Matter and Materials', 'Pending'),
('Class 5', 'EVS', 'Work, Force and Energy', 'Pending'),
('Class 5', 'EVS', 'Simple Machines', 'Pending'),
('Class 5', 'EVS', 'Light and Sound', 'Pending'),
('Class 5', 'EVS', 'Rocks and Soil', 'Pending'),
('Class 5', 'EVS', 'Shelter and Housing', 'Pending'),
('Class 5', 'EVS', 'Travel and Communication', 'Pending'),
('Class 5', 'EVS', 'Grasslands and Forests', 'Pending'),
('Class 5', 'EVS', 'Soil Conservation', 'Pending'),
('Class 5', 'EVS', 'The Moon (Phases and Features)', 'Pending'),
('Class 5', 'EVS', 'Natural Resources and Their Conservation', 'Pending'),
('Class 5', 'Social Science', 'Our Country - India', 'Pending'),
('Class 5', 'Social Science', 'Latitudes and Longitudes', 'Pending'),
('Class 5', 'Social Science', 'Movements of the Earth', 'Pending'),
('Class 5', 'Social Science', 'Major Landforms of the World', 'Pending'),
('Class 5', 'Social Science', 'Climate and Weather', 'Pending'),
('Class 5', 'Social Science', 'Natural Vegetation and Wildlife', 'Pending'),
('Class 5', 'Social Science', 'Water Resources', 'Pending'),
('Class 5', 'Social Science', 'Agriculture and Industries', 'Pending'),
('Class 5', 'Social Science', 'Transport and Communication', 'Pending'),
('Class 5', 'Social Science', 'Natural Resources and Conservation', 'Pending'),
('Class 5', 'Social Science', 'The United Nations (Basic Introduction)', 'Pending'),
('Class 5', 'Social Science', 'Indian Freedom Struggle (Basic Overview)', 'Pending'),
('Class 5', 'Social Science', 'National Leaders of India', 'Pending'),
('Class 5', 'Social Science', 'The Constitution of India (Basic Introduction)', 'Pending'),
('Class 5', 'Social Science', 'Fundamental Rights and Duties', 'Pending'),
('Class 5', 'Social Science', 'Local Self-Government (Panchayati Raj and Municipal Corporation)', 'Pending'),
('Class 5', 'Social Science', 'Rural and Urban Administration', 'Pending'),
('Class 5', 'Social Science', 'Democracy and Government', 'Pending'),
('Class 5', 'Social Science', 'Population and Occupations', 'Pending'),
('Class 5', 'Social Science', 'Disaster Management', 'Pending'),
('Class 5', 'Social Science', 'Environmental Issues', 'Pending'),
('Class 5', 'Social Science', 'Heritage and Culture of India', 'Pending'),
('Class 5', 'Social Science', 'Monuments and Historical Places', 'Pending'),
('Class 5', 'Social Science', 'Maps and Globes', 'Pending'),
('Class 5', 'Social Science', 'Continents and Oceans', 'Pending'),
('Class 6', 'Maths', 'Patterns in Mathematics', 'Pending'),
('Class 6', 'Maths', 'Lines and Angles', 'Pending'),
('Class 6', 'Maths', 'Number Play', 'Pending'),
('Class 6', 'Maths', 'Data Handling and Presentation', 'Pending'),
('Class 6', 'Maths', 'Prime Time', 'Pending'),
('Class 6', 'Maths', 'Perimeter and Area', 'Pending'),
('Class 6', 'Maths', 'Fractions', 'Pending'),
('Class 6', 'Maths', 'Playing with Constructions', 'Pending'),
('Class 6', 'Maths', 'Symmetry', 'Pending'),
('Class 6', 'Maths', 'The Other Side of Zero', 'Pending'),
('Class 6', 'Science', 'The Wonderful World of Science', 'Pending'),
('Class 6', 'Science', 'Diversity in the Living World', 'Pending'),
('Class 6', 'Science', 'Mindful Eating: A Path to a Healthy Body', 'Pending'),
('Class 6', 'Science', 'Exploring Magnets', 'Pending'),
('Class 6', 'Science', 'Measurement of Length and Motion', 'Pending'),
('Class 6', 'Science', 'Materials Around Us', 'Pending'),
('Class 6', 'Science', 'Temperature and Its Measurement', 'Pending'),
('Class 6', 'Science', 'A Journey Through States of Water', 'Pending'),
('Class 6', 'Science', 'Methods of Separation in Everyday Life', 'Pending'),
('Class 6', 'Science', 'Living Creatures: Exploring Their Characteristics', 'Pending'),
('Class 6', 'Science', 'Nature\'s Treasures', 'Pending'),
('Class 6', 'Science', 'Beyond Earth', 'Pending'),
('Class 6', 'English Grammar', 'Nouns (Kinds of Nouns)', 'Pending'),
('Class 6', 'English Grammar', 'Number and Gender', 'Pending'),
('Class 6', 'English Grammar', 'Pronouns', 'Pending'),
('Class 6', 'English Grammar', 'Adjectives', 'Pending'),
('Class 6', 'English Grammar', 'Articles (A, An, The)', 'Pending'),
('Class 6', 'English Grammar', 'Verbs (Transitive and Intransitive)', 'Pending'),
('Class 6', 'English Grammar', 'Subject-Verb Agreement', 'Pending'),
('Class 6', 'English Grammar', 'Tenses (Present, Past, Future)', 'Pending'),
('Class 6', 'English Grammar', 'Continuous and Perfect Tenses (Basic)', 'Pending'),
('Class 6', 'English Grammar', 'Adverbs', 'Pending'),
('Class 6', 'English Grammar', 'Prepositions', 'Pending'),
('Class 6', 'English Grammar', 'Conjunctions', 'Pending'),
('Class 6', 'English Grammar', 'Interjections', 'Pending'),
('Class 6', 'English Grammar', 'Kinds of Sentences', 'Pending'),
('Class 6', 'English Grammar', 'Active and Passive Voice (Introduction)', 'Pending'),
('Class 6', 'English Grammar', 'Direct and Indirect Speech (Introduction)', 'Pending'),
('Class 6', 'English Grammar', 'Punctuation', 'Pending'),
('Class 6', 'English Grammar', 'Degrees of Comparison', 'Pending'),
('Class 6', 'English Grammar', 'Modals (Can, May, Must, Should)', 'Pending'),
('Class 6', 'English Grammar', 'Synonyms and Antonyms', 'Pending'),
('Class 6', 'English Grammar', 'Homophones and Homonyms', 'Pending'),
('Class 6', 'English Grammar', 'Idioms and Phrases', 'Pending'),
('Class 6', 'English Grammar', 'Vocabulary Building', 'Pending'),
('Class 6', 'English Grammar', 'Sentence Transformation', 'Pending'),
('Class 6', 'English Grammar', 'Paragraph Writing', 'Pending'),
('Class 6', 'English Grammar', 'Letter Writing (Formal and Informal)', 'Pending'),
('Class 6', 'English Grammar', 'Notice Writing', 'Pending'),
('Class 6', 'English Grammar', 'Message Writing', 'Pending'),
('Class 6', 'English Grammar', 'Story Writing', 'Pending'),
('Class 6', 'English Grammar', 'Comprehension (Unseen Passage)', 'Pending'),
('Class 6', 'Social Science', 'Locating Places on the Earth', 'Pending'),
('Class 6', 'Social Science', 'Oceans and Continents', 'Pending'),
('Class 6', 'Social Science', 'Landforms and Life', 'Pending'),
('Class 6', 'Social Science', 'Timeline and Sources of History', 'Pending'),
('Class 6', 'Social Science', 'India, That Is Bharat', 'Pending'),
('Class 6', 'Social Science', 'The Beginnings of Indian Civilisation', 'Pending'),
('Class 6', 'Social Science', 'India\'s Cultural Roots', 'Pending'),
('Class 6', 'Social Science', 'Unity in Diversity, or Many in the One', 'Pending'),
('Class 6', 'Social Science', 'Family and Community', 'Pending'),
('Class 6', 'Social Science', 'Grassroots Democracy - Part 1: Governance', 'Pending'),
('Class 6', 'Social Science', 'Grassroots Democracy - Part 2: Local Government in Rural Areas', 'Pending'),
('Class 6', 'Social Science', 'Grassroots Democracy - Part 3: Local Government in Urban Areas', 'Pending'),
('Class 6', 'Social Science', 'The Value of Work', 'Pending'),
('Class 6', 'Social Science', 'Economic Activities Around Us', 'Pending'),
('Class 7', 'Maths', 'Large Numbers Around Us', 'Pending'),
('Class 7', 'Maths', 'Arithmetic Expressions', 'Pending'),
('Class 7', 'Maths', 'A Peek Beyond the Point (Decimals)', 'Pending'),
('Class 7', 'Maths', 'Expressions Using Letter Numbers (Algebra)', 'Pending'),
('Class 7', 'Maths', 'Parallel and Intersecting Lines', 'Pending'),
('Class 7', 'Maths', 'Number Play', 'Pending'),
('Class 7', 'Maths', 'A Tale of Three Intersecting Lines (Triangles)', 'Pending'),
('Class 7', 'Maths', 'Working with Fractions', 'Pending'),
('Class 7', 'Science', 'The Ever-Evolving World of Science', 'Pending'),
('Class 7', 'Science', 'Exploring Substances: Acidic, Basic, Neutral', 'Pending'),
('Class 7', 'Science', 'Electricity: Circuits and Their Components', 'Pending'),
('Class 7', 'Science', 'The World of Metals and Non-Metals', 'Pending'),
('Class 7', 'Science', 'Changes Around Us: Physical and Chemical', 'Pending'),
('Class 7', 'Science', 'Adolescence: A Stage of Growth and Change', 'Pending'),
('Class 7', 'Science', 'Heat Transfer in Nature', 'Pending'),
('Class 7', 'Science', 'Measurement of Time and Motion', 'Pending'),
('Class 7', 'Science', 'Life Processes in Animals', 'Pending'),
('Class 7', 'Science', 'Life Processes in Plants', 'Pending'),
('Class 7', 'Science', 'Light: Shadows and Reflections', 'Pending'),
('Class 7', 'Science', 'Earth, Moon, and the Sun', 'Pending'),
('Class 7', 'English Grammar', 'Nouns (Kinds and Functions)', 'Pending'),
('Class 7', 'English Grammar', 'Pronouns and Their Types', 'Pending'),
('Class 7', 'English Grammar', 'Adjectives and Degrees of Comparison', 'Pending'),
('Class 7', 'English Grammar', 'Articles and Determiners', 'Pending'),
('Class 7', 'English Grammar', 'Verbs (Transitive and Intransitive)', 'Pending'),
('Class 7', 'English Grammar', 'Subject-Verb Agreement', 'Pending'),
('Class 7', 'English Grammar', 'Tenses (Present, Past and Future)', 'Pending'),
('Class 7', 'English Grammar', 'Perfect and Continuous Tenses', 'Pending'),
('Class 7', 'English Grammar', 'Modals', 'Pending'),
('Class 7', 'English Grammar', 'Adverbs', 'Pending'),
('Class 7', 'English Grammar', 'Prepositions', 'Pending'),
('Class 7', 'English Grammar', 'Conjunctions', 'Pending'),
('Class 7', 'English Grammar', 'Interjections', 'Pending'),
('Class 7', 'English Grammar', 'Active and Passive Voice', 'Pending'),
('Class 7', 'English Grammar', 'Direct and Indirect Speech', 'Pending'),
('Class 7', 'English Grammar', 'Punctuation', 'Pending'),
('Class 7', 'English Grammar', 'Kinds of Sentences', 'Pending'),
('Class 7', 'English Grammar', 'Sentence Transformation', 'Pending'),
('Class 7', 'English Grammar', 'Phrases and Clauses', 'Pending'),
('Class 7', 'English Grammar', 'Synonyms and Antonyms', 'Pending'),
('Class 7', 'English Grammar', 'Homophones', 'Pending'),
('Class 7', 'English Grammar', 'Idioms and Phrases', 'Pending'),
('Class 7', 'English Grammar', 'Paragraph Writing', 'Pending'),
('Class 7', 'English Grammar', 'Letter Writing (Formal and Informal)', 'Pending'),
('Class 7', 'English Grammar', 'Notice Writing', 'Pending'),
('Class 7', 'English Grammar', 'Story Writing', 'Pending'),
('Class 7', 'English Grammar', 'Comprehension (Unseen Passage)', 'Pending'),
('Class 7', 'Social Science', 'Geographical Diversity of India', 'Pending'),
('Class 7', 'Social Science', 'Understanding the Weather', 'Pending'),
('Class 7', 'Social Science', 'Climate of India', 'Pending'),
('Class 7', 'Social Science', 'New Beginnings: Cities and States', 'Pending'),
('Class 7', 'Social Science', 'The Rise of Empires', 'Pending'),
('Class 7', 'Social Science', 'The Age of Reorganisation', 'Pending'),
('Class 7', 'Social Science', 'The Gupta Era: An Age of Creativity', 'Pending'),
('Class 7', 'Social Science', 'How the Land Becomes Sacred', 'Pending'),
('Class 7', 'Social Science', 'From the Rulers to the Ruled: Types of Governments', 'Pending'),
('Class 7', 'Social Science', 'The Constitution of India: An Introduction', 'Pending'),
('Class 7', 'Social Science', 'From Barter to Money', 'Pending'),
('Class 7', 'Social Science', 'Understanding Markets', 'Pending'),
('Class 7', 'Social Science', 'The Story of Indian Farming', 'Pending'),
('Class 7', 'Social Science', 'India and Her Neighbours', 'Pending'),
('Class 7', 'Social Science', 'Empires and Kingdoms: 6th to 10th Centuries', 'Pending'),
('Class 7', 'Social Science', 'Turning Tides: 11th and 12th Centuries', 'Pending'),
('Class 7', 'Social Science', 'India, a Home to Many', 'Pending'),
('Class 7', 'Social Science', 'The State, the Government, and You', 'Pending'),
('Class 7', 'Social Science', 'Infrastructure: Engine of India\'s Development', 'Pending'),
('Class 7', 'Social Science', 'Banks and the Magic of Finance', 'Pending'),
('Class 8', 'Maths', 'Squares and Square Roots, Cubes and Cube Roots', 'Pending'),
('Class 8', 'Maths', 'Exponents and Powers', 'Pending'),
('Class 8', 'Maths', 'Rational Numbers', 'Pending'),
('Class 8', 'Maths', 'Understanding Quadrilaterals', 'Pending'),
('Class 8', 'Maths', 'Playing with Numbers', 'Pending'),
('Class 8', 'Maths', 'Algebraic Expressions and Identities, Factorisation', 'Pending'),
('Class 8', 'Maths', 'Direct and Inverse Proportions', 'Pending'),
('Class 8', 'Maths', 'Fractions in Disguise', 'Pending'),
('Class 8', 'Maths', 'Pythagoras Theorem', 'Pending'),
('Class 8', 'Maths', 'Comparing Quantities', 'Pending'),
('Class 8', 'Maths', 'Practical Geometry', 'Pending'),
('Class 8', 'Maths', 'Geometric Constructions', 'Pending'),
('Class 8', 'Maths', 'Linear Equations in One Variable', 'Pending'),
('Class 8', 'Maths', 'Mensuration (Area)', 'Pending'),
('Class 8', 'Science', 'Exploring the Investigative World of Science', 'Pending'),
('Class 8', 'Science', 'The Invisible Living World: Beyond Our Naked Eye', 'Pending'),
('Class 8', 'Science', 'Health: The Ultimate Treasure', 'Pending'),
('Class 8', 'Science', 'Electricity: Magnetic and Heating Effects', 'Pending'),
('Class 8', 'Science', 'Exploring Forces', 'Pending'),
('Class 8', 'Science', 'Pressure, Winds, Storms and Cyclones', 'Pending'),
('Class 8', 'Science', 'Particulate Nature of Matter', 'Pending'),
('Class 8', 'Science', 'Nature of Matter: Elements, Compounds and Mixtures', 'Pending'),
('Class 8', 'Science', 'The Amazing World of Solutes, Solvents and Solutions', 'Pending'),
('Class 8', 'Science', 'Light: Mirrors and Lenses', 'Pending'),
('Class 8', 'Science', 'Keeping Time with the Skies', 'Pending'),
('Class 8', 'Science', 'How Nature Works in Harmony', 'Pending'),
('Class 8', 'Science', 'Our Home: Earth - A Unique Life Sustaining Planet', 'Pending'),
('Class 8', 'English Grammar', 'Nouns (Kinds and Usage)', 'Pending'),
('Class 8', 'English Grammar', 'Pronouns and Their Types', 'Pending'),
('Class 8', 'English Grammar', 'Determiners and Articles', 'Pending'),
('Class 8', 'English Grammar', 'Adjectives and Degrees of Comparison', 'Pending'),
('Class 8', 'English Grammar', 'Verbs (Transitive and Intransitive)', 'Pending'),
('Class 8', 'English Grammar', 'Subject-Verb Agreement', 'Pending'),
('Class 8', 'English Grammar', 'Tenses (Present, Past, Future)', 'Pending'),
('Class 8', 'English Grammar', 'Perfect and Continuous Tenses', 'Pending'),
('Class 8', 'English Grammar', 'Modals', 'Pending'),
('Class 8', 'English Grammar', 'Adverbs', 'Pending'),
('Class 8', 'English Grammar', 'Prepositions', 'Pending'),
('Class 8', 'English Grammar', 'Conjunctions', 'Pending'),
('Class 8', 'English Grammar', 'Interjections', 'Pending'),
('Class 8', 'English Grammar', 'Active and Passive Voice', 'Pending'),
('Class 8', 'English Grammar', 'Direct and Indirect Speech', 'Pending'),
('Class 8', 'English Grammar', 'Punctuation', 'Pending'),
('Class 8', 'English Grammar', 'Kinds of Sentences', 'Pending'),
('Class 8', 'English Grammar', 'Sentence Transformation', 'Pending'),
('Class 8', 'English Grammar', 'Phrases and Clauses', 'Pending'),
('Class 8', 'English Grammar', 'Reported Speech', 'Pending'),
('Class 8', 'English Grammar', 'Synonyms and Antonyms', 'Pending'),
('Class 8', 'English Grammar', 'Idioms and Phrases', 'Pending'),
('Class 8', 'English Grammar', 'Vocabulary Building', 'Pending'),
('Class 8', 'English Grammar', 'Paragraph Writing', 'Pending'),
('Class 8', 'English Grammar', 'Letter Writing (Formal and Informal)', 'Pending'),
('Class 8', 'English Grammar', 'Notice Writing', 'Pending'),
('Class 8', 'English Grammar', 'Message Writing', 'Pending'),
('Class 8', 'English Grammar', 'Story Writing', 'Pending'),
('Class 8', 'English Grammar', 'Essay Writing', 'Pending'),
('Class 8', 'English Grammar', 'Comprehension (Unseen Passage)', 'Pending'),
('Class 8', 'Social Science', 'Natural Resources and Their Use', 'Pending'),
('Class 8', 'Social Science', 'Reshaping India\'s Political Map', 'Pending'),
('Class 8', 'Social Science', 'The Rise of the Marathas', 'Pending'),
('Class 8', 'Social Science', 'The Colonial Era in India', 'Pending'),
('Class 8', 'Social Science', 'Universal Franchise and India\'s Electoral System', 'Pending'),
('Class 8', 'Social Science', 'The Parliamentary System: Legislature and Executive', 'Pending'),
('Class 8', 'Social Science', 'Factors of Production', 'Pending'),
('Class 9', 'Maths', 'Uses of Coordinates', 'Pending'),
('Class 9', 'Maths', 'Number Systems', 'Pending'),
('Class 9', 'Maths', 'Polynomials', 'Pending'),
('Class 9', 'Maths', 'Linear Equations in Two Variables', 'Pending'),
('Class 9', 'Maths', 'Introduction to Euclid\'s Geometry', 'Pending'),
('Class 9', 'Maths', 'Lines and Angles', 'Pending'),
('Class 9', 'Maths', 'Triangles', 'Pending'),
('Class 9', 'Maths', 'Quadrilaterals', 'Pending'),
('Class 9', 'Maths', 'Areas of Parallelograms and Triangles', 'Pending'),
('Class 9', 'Maths', 'Circles', 'Pending'),
('Class 9', 'Maths', 'Constructions', 'Pending'),
('Class 9', 'Maths', 'Heron\'s Formula', 'Pending'),
('Class 9', 'Maths', 'Surface Areas and Volumes', 'Pending'),
('Class 9', 'Maths', 'Statistics', 'Pending'),
('Class 9', 'Maths', 'Probability', 'Pending'),
('Class 9', 'Science', 'Exploration: Entering the World of Secondary Science', 'Pending'),
('Class 9', 'Science', 'Cell: The Building Block of Life', 'Pending'),
('Class 9', 'Science', 'Tissues in Action', 'Pending'),
('Class 9', 'Science', 'Describing Motion Around Us', 'Pending'),
('Class 9', 'Science', 'Exploring Mixtures and their Separation', 'Pending'),
('Class 9', 'Science', 'How Forces Affect Motion', 'Pending'),
('Class 9', 'Science', 'Work, Energy and Simple Machines', 'Pending'),
('Class 9', 'Science', 'Journey Inside the Atom', 'Pending'),
('Class 9', 'Science', 'Atomic Foundations of Matter', 'Pending'),
('Class 9', 'Science', 'Sound Waves: Characteristics and Applications', 'Pending'),
('Class 9', 'Science', 'Reproduction: How Life Continues', 'Pending'),
('Class 9', 'Science', 'Patterns in Life: Diversity and Classification', 'Pending'),
('Class 9', 'Science', 'Earth as a System: Energy, Matter, and Life', 'Pending'),
('Class 9', 'English Grammar', 'Tenses (Present, Past, Future)', 'Pending'),
('Class 9', 'English Grammar', 'Modals', 'Pending'),
('Class 9', 'English Grammar', 'Subject-Verb Agreement', 'Pending'),
('Class 9', 'English Grammar', 'Determiners', 'Pending'),
('Class 9', 'English Grammar', 'Articles', 'Pending'),
('Class 9', 'English Grammar', 'Prepositions', 'Pending'),
('Class 9', 'English Grammar', 'Conjunctions', 'Pending'),
('Class 9', 'English Grammar', 'Adverbs', 'Pending'),
('Class 9', 'English Grammar', 'Active and Passive Voice', 'Pending'),
('Class 9', 'English Grammar', 'Direct and Indirect Speech', 'Pending'),
('Class 9', 'English Grammar', 'Clauses (Noun, Adjective, Adverb Clauses)', 'Pending'),
('Class 9', 'English Grammar', 'Phrases', 'Pending'),
('Class 9', 'English Grammar', 'Sentence Transformation', 'Pending'),
('Class 9', 'English Grammar', 'Reported Speech', 'Pending'),
('Class 9', 'English Grammar', 'Editing and Omission', 'Pending'),
('Class 9', 'English Grammar', 'Rearrangement of Sentences', 'Pending'),
('Class 9', 'English Grammar', 'Gap Filling', 'Pending'),
('Class 9', 'English Grammar', 'Error Correction', 'Pending'),
('Class 9', 'English Grammar', 'Punctuation', 'Pending'),
('Class 9', 'English Grammar', 'Synonyms and Antonyms', 'Pending'),
('Class 9', 'English Grammar', 'Idioms and Phrases', 'Pending'),
('Class 9', 'English Grammar', 'Vocabulary Building', 'Pending'),
('Class 9', 'English Grammar', 'Paragraph Writing', 'Pending'),
('Class 9', 'English Grammar', 'Story Writing', 'Pending'),
('Class 9', 'English Grammar', 'Article Writing', 'Pending'),
('Class 9', 'English Grammar', 'Letter Writing (Formal and Informal)', 'Pending'),
('Class 9', 'English Grammar', 'Speech Writing', 'Pending'),
('Class 9', 'English Grammar', 'Diary Entry', 'Pending'),
('Class 9', 'English Grammar', 'Comprehension (Unseen Passage)', 'Pending'),
('Class 9', 'Social Science', 'Social Science: Meaning, Scope and Importance', 'Pending'),
('Class 9', 'Social Science', 'India: Size, Location and Physical Features', 'Pending'),
('Class 9', 'Social Science', 'Climate and Natural Vegetation', 'Pending'),
('Class 9', 'Social Science', 'Population and Human Resources', 'Pending'),
('Class 9', 'Social Science', 'Understanding History: Sources and Timeline', 'Pending'),
('Class 9', 'Social Science', 'Ancient Civilisations and Their Legacy', 'Pending'),
('Class 9', 'Social Science', 'Medieval India: Society and Culture', 'Pending'),
('Class 9', 'Social Science', 'Colonialism and Its Impact', 'Pending'),
('Class 9', 'Social Science', 'Democracy: Meaning and Features', 'Pending'),
('Class 9', 'Social Science', 'The Constitution of India', 'Pending'),
('Class 9', 'Social Science', 'Electoral Politics and Governance', 'Pending'),
('Class 9', 'Social Science', 'Economic Activities: Production and Distribution', 'Pending'),
('Class 9', 'Social Science', 'Poverty, Inequality and Development', 'Pending'),
('Class 9', 'Social Science', 'Natural Resources and Sustainable Development', 'Pending'),
('Class 10', 'Maths', 'Real Numbers', 'Pending'),
('Class 10', 'Maths', 'Polynomials', 'Pending'),
('Class 10', 'Maths', 'Pair of Linear Equations in Two Variables', 'Pending'),
('Class 10', 'Maths', 'Quadratic Equations', 'Pending'),
('Class 10', 'Maths', 'Arithmetic Progressions', 'Pending'),
('Class 10', 'Maths', 'Triangles', 'Pending'),
('Class 10', 'Maths', 'Coordinate Geometry', 'Pending'),
('Class 10', 'Maths', 'Trigonometric Identities', 'Pending'),
('Class 10', 'Maths', 'Heights and Distances', 'Pending'),
('Class 10', 'Maths', 'Circles', 'Pending'),
('Class 10', 'Maths', 'Constructions', 'Pending'),
('Class 10', 'Maths', 'Areas Related to Circles', 'Pending'),
('Class 10', 'Maths', 'Surface Areas and Volumes', 'Pending'),
('Class 10', 'Maths', 'Statistics', 'Pending'),
('Class 10', 'Maths', 'Probability', 'Pending'),
('Class 10', 'Science', 'Chemical Reactions and Equations', 'Pending'),
('Class 10', 'Science', 'Acids, Bases and Salts', 'Pending'),
('Class 10', 'Science', 'Metals and Non-metals', 'Pending'),
('Class 10', 'Science', 'Carbon and Its Compounds', 'Pending'),
('Class 10', 'Science', 'Periodic Classification of Elements', 'Pending'),
('Class 10', 'Science', 'Life Processes', 'Pending'),
('Class 10', 'Science', 'Control and Coordination', 'Pending'),
('Class 10', 'Science', 'How Do Organisms Reproduce', 'Pending'),
('Class 10', 'Science', 'Heredity and Evolution', 'Pending'),
('Class 10', 'Science', 'Light - Reflection and Refraction', 'Pending'),
('Class 10', 'Science', 'The Human Eye and the Colourful World', 'Pending'),
('Class 10', 'Science', 'Electricity', 'Pending'),
('Class 10', 'Science', 'Magnetic Effects of Electric Current', 'Pending'),
('Class 10', 'Science', 'Sources of Energy', 'Pending'),
('Class 10', 'Science', 'Our Environment', 'Pending'),
('Class 10', 'Science', 'Management of Natural Resources', 'Pending'),
('Class 10', 'English Grammar', 'Tenses', 'Pending'),
('Class 10', 'English Grammar', 'Modals', 'Pending'),
('Class 10', 'English Grammar', 'Subject-Verb Agreement', 'Pending'),
('Class 10', 'English Grammar', 'Determiners', 'Pending'),
('Class 10', 'English Grammar', 'Articles', 'Pending'),
('Class 10', 'English Grammar', 'Prepositions', 'Pending'),
('Class 10', 'English Grammar', 'Conjunctions', 'Pending'),
('Class 10', 'English Grammar', 'Adverbs', 'Pending'),
('Class 10', 'English Grammar', 'Active and Passive Voice', 'Pending'),
('Class 10', 'English Grammar', 'Direct and Indirect Speech', 'Pending'),
('Class 10', 'English Grammar', 'Clauses (Noun, Adjective, Adverb Clauses)', 'Pending'),
('Class 10', 'English Grammar', 'Phrases', 'Pending'),
('Class 10', 'English Grammar', 'Sentence Transformation', 'Pending'),
('Class 10', 'English Grammar', 'Editing and Omission', 'Pending'),
('Class 10', 'English Grammar', 'Rearrangement of Sentences', 'Pending'),
('Class 10', 'English Grammar', 'Gap Filling', 'Pending'),
('Class 10', 'English Grammar', 'Error Correction', 'Pending'),
('Class 10', 'English Grammar', 'Reported Speech', 'Pending'),
('Class 10', 'English Grammar', 'Punctuation', 'Pending'),
('Class 10', 'English Grammar', 'Synonyms and Antonyms', 'Pending'),
('Class 10', 'English Grammar', 'Idioms and Phrases', 'Pending'),
('Class 10', 'English Grammar', 'Vocabulary Building', 'Pending'),
('Class 10', 'English Grammar', 'Formal Letter Writing', 'Pending'),
('Class 10', 'English Grammar', 'Letter to the Editor', 'Pending'),
('Class 10', 'English Grammar', 'Article Writing', 'Pending'),
('Class 10', 'English Grammar', 'Speech Writing', 'Pending'),
('Class 10', 'English Grammar', 'Report Writing', 'Pending'),
('Class 10', 'English Grammar', 'Analytical Paragraph Writing', 'Pending'),
('Class 10', 'English Grammar', 'Story Writing', 'Pending'),
('Class 10', 'English Grammar', 'Comprehension (Unseen Passage)', 'Pending'),
('Class 10', 'Social Science', 'The Rise of Nationalism in Europe', 'Pending'),
('Class 10', 'Social Science', 'Nationalism in India', 'Pending'),
('Class 10', 'Social Science', 'The Making of a Global World', 'Pending'),
('Class 10', 'Social Science', 'The Age of Industrialisation', 'Pending'),
('Class 10', 'Social Science', 'Print Culture and the Modern World', 'Pending'),
('Class 10', 'Social Science', 'Resources and Development', 'Pending'),
('Class 10', 'Social Science', 'Forest and Wildlife Resources', 'Pending'),
('Class 10', 'Social Science', 'Water Resources', 'Pending'),
('Class 10', 'Social Science', 'Agriculture', 'Pending'),
('Class 10', 'Social Science', 'Minerals and Energy Resources', 'Pending'),
('Class 10', 'Social Science', 'Manufacturing Industries', 'Pending'),
('Class 10', 'Social Science', 'Lifelines of National Economy', 'Pending'),
('Class 10', 'Social Science', 'Power Sharing', 'Pending'),
('Class 10', 'Social Science', 'Federalism', 'Pending'),
('Class 10', 'Social Science', 'Gender, Religion and Caste', 'Pending'),
('Class 10', 'Social Science', 'Political Parties', 'Pending'),
('Class 10', 'Social Science', 'Outcomes of Democracy', 'Pending'),
('Class 10', 'Social Science', 'Challenges to Democracy', 'Pending'),
('Class 10', 'Social Science', 'Development', 'Pending'),
('Class 10', 'Social Science', 'Sectors of the Indian Economy', 'Pending'),
('Class 10', 'Social Science', 'Money and Credit', 'Pending'),
('Class 10', 'Social Science', 'Globalisation and the Indian Economy', 'Pending'),
('Class 10', 'Social Science', 'Consumer Rights', 'Pending');
